# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: java
      - name: Build
        run: bash .github/workflows/build.sh
      - name: Prepare artifact
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging