# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Release
on:
  push:
    tags:
      - '1.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package_${{ github.ref_name }}
          path: staging
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sandbox-gh-actions-0.0.1-SNAPSHOT.jar
            staging/sandbox-gh-actions-0.0.1-SNAPSHOT.jar
